### PR TITLE
tests: fail on any warnings

### PR DESCRIPTION
**Pull request by skshetry**
So that we can find out issues like https://github.com/iterative/pytest-servers/issues/43.

### CODE REVIEW

**Comment by dtrifiro** [comment]
I guess we could merge this, assuming we `continue-on-error` on pypy3.8, for now:
```git
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index b9cbebf..9860135 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -43,11 +43,11 @@ jobs:
         nox --version
 
     - name: Lint code and check dependencies
-      continue-on-error: ${{ matrix.nox_pyv == '3.11' }}
+      continue-on-error: ${{ matrix.nox_pyv == '3.11' || matrix.nox_pyv == "pypy3.8" }}
       run: nox -s lint safety
 
     - name: Run tests
-      continue-on-error: ${{ matrix.nox_pyv == '3.11' }}
+      continue-on-error: ${{ matrix.nox_pyv == '3.11' || matrix.nox_py == "pypy3.8" }}
       run: nox -s tests-${{ matrix.nox_pyv || matrix.pyv }}
       shell: bash
       env:
```

**Comment by skshetry** [comment]
@dtrifiro, it seems to be failing correctly though, no?

https://github.com/iterative/pytest-servers/runs/8033979471?check_suite_focus=true#step:6:917

```
self = <Element 'Error' at 0x537cf70>

    def __bool__(self):
        warnings.warn(
            "The behavior of this method will change in future versions.  "
            "Use specific 'len(elem)' or 'elem is not None' test instead.",
>           FutureWarning, stacklevel=2
            )
E       FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.

```

**Comment by dtrifiro** [comment]
I guess the main problem I see here is that any warnings emitted by dependencies will make CI fail, in this case the failure we're getting (only on pypy3.8 for some reason 🤔), is due to us calling `mkdir` on adlfs, which in turns relies on `azure-storage-blob`  which is raising the `FutureWarning` from `azure-core`. There's not much we can do about it here, and it goes pretty deep down the stack. 

Do we really want to have these kind of warnings fail CI?

**Comment by skshetry** [comment]
My main motivation was to catch resource leaks that might happen in `dvc-data` and `dvc-objects`.

**Pull request closed without merging**
